services:
  signer: 
    build:
      context: .
      dockerfile: ./packages/signer/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379" # Maps host port 6379 to container port 6379