packages:
  - packages/**
  - apps/**

catalog:
  "@biomejs/biome": ^2.2.4
  "@types/react": 19.2.0
  "@types/react-dom": 19.2.0
  o1js: 2.4.0
  oxlint: ^1.16.0
  oxlint-tsgolint: ^0.2.0
  react: 19.2.0
  react-dom: 19.2.0
  wrangler: 4.40.3

onlyBuiltDependencies:
  - lefthook

patchedDependencies:
  "@gql.tada/internal": patches/@gql.tada__internal.patch
