// Generated by Wrangler by running `wrangler types`

import type { TokenList } from "./src/do"

export interface Env {
	TOKENLIST: DurableObjectNamespace<TokenList>
	ASSETS: Fetcher
}
declare module "*.sql" {
	const value: string
	export default value
}
