services:
  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379" # Maps host port 6379 to container port 6379

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: signer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
