// dprint-ignore-file
/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'CreateMultisigInput': { kind: 'INPUT_OBJECT'; name: 'CreateMultisigInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'deadline'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'network'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Network'; ofType: null; }; }; defaultValue: null }, { name: 'signature'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'signerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
    'CreatePoolInput': { kind: 'INPUT_OBJECT'; name: 'CreatePoolInput'; isOneOf: false; inputFields: [{ name: 'network'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Network'; ofType: null; }; }; defaultValue: null }, { name: 'tokenA'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'tokenB'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'CreateSignerInput': { kind: 'INPUT_OBJECT'; name: 'CreateSignerInput'; isOneOf: false; inputFields: [{ name: 'publicKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'CreateSignerNetworkInput': { kind: 'INPUT_OBJECT'; name: 'CreateSignerNetworkInput'; isOneOf: false; inputFields: [{ name: 'active'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'network'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Network'; ofType: null; }; }; defaultValue: null }, { name: 'permission'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'signerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
    'Date': unknown;
    'DeployFactoryInput': { kind: 'INPUT_OBJECT'; name: 'DeployFactoryInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'delegator'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'deployer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'network'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Network'; ofType: null; }; }; defaultValue: null }, { name: 'protocol'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'FactoryJobResult': { kind: 'OBJECT'; name: 'FactoryJobResult'; fields: { 'completedAt': { name: 'completedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Date'; ofType: null; }; } }; 'factoryPublicKey': { name: 'factoryPublicKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'transactionJson': { name: 'transactionJson'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Int': unknown;
    'Job': { kind: 'OBJECT'; name: 'Job'; fields: { 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'JobResult': { kind: 'OBJECT'; name: 'JobResult'; fields: { 'completedAt': { name: 'completedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Date'; ofType: null; }; } }; 'poolPublicKey': { name: 'poolPublicKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'transactionJson': { name: 'transactionJson'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Multisig': { kind: 'OBJECT'; name: 'Multisig'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'data': { name: 'data'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'deadline': { name: 'deadline'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'network': { name: 'network'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'signature': { name: 'signature'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'signer': { name: 'signer'; type: { kind: 'OBJECT'; name: 'Signer'; ofType: null; } }; 'signerId': { name: 'signerId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'confirmFactoryJob': { name: 'confirmFactoryJob'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'confirmJob': { name: 'confirmJob'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'createMultisig': { name: 'createMultisig'; type: { kind: 'OBJECT'; name: 'Multisig'; ofType: null; } }; 'createPool': { name: 'createPool'; type: { kind: 'OBJECT'; name: 'Job'; ofType: null; } }; 'createSigner': { name: 'createSigner'; type: { kind: 'OBJECT'; name: 'Signer'; ofType: null; } }; 'createSignerNetwork': { name: 'createSignerNetwork'; type: { kind: 'OBJECT'; name: 'SignerNetwork'; ofType: null; } }; 'deleteMultisig': { name: 'deleteMultisig'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'deployFactory': { name: 'deployFactory'; type: { kind: 'OBJECT'; name: 'Job'; ofType: null; } }; 'updateSigner': { name: 'updateSigner'; type: { kind: 'OBJECT'; name: 'Signer'; ofType: null; } }; 'updateSignerNetwork': { name: 'updateSignerNetwork'; type: { kind: 'OBJECT'; name: 'SignerNetwork'; ofType: null; } }; }; };
    'Network': { name: 'Network'; enumValues: 'mina_devnet' | 'mina_mainnet' | 'zeko_mainnet' | 'zeko_testnet'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'factoryDeploymentJob': { name: 'factoryDeploymentJob'; type: { kind: 'OBJECT'; name: 'FactoryJobResult'; ofType: null; } }; 'multisig': { name: 'multisig'; type: { kind: 'OBJECT'; name: 'Multisig'; ofType: null; } }; 'multisigs': { name: 'multisigs'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Multisig'; ofType: null; }; }; } }; 'poolCreationJob': { name: 'poolCreationJob'; type: { kind: 'OBJECT'; name: 'JobResult'; ofType: null; } }; 'signer': { name: 'signer'; type: { kind: 'OBJECT'; name: 'Signer'; ofType: null; } }; 'signers': { name: 'signers'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Signer'; ofType: null; }; }; } }; }; };
    'Signer': { kind: 'OBJECT'; name: 'Signer'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'networks': { name: 'networks'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SignerNetwork'; ofType: null; }; }; } }; 'publicKey': { name: 'publicKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'SignerNetwork': { kind: 'OBJECT'; name: 'SignerNetwork'; fields: { 'active': { name: 'active'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'network': { name: 'network'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'permission': { name: 'permission'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'signerId': { name: 'signerId'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'String': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'factoryDeployment': { name: 'factoryDeployment'; type: { kind: 'OBJECT'; name: 'FactoryJobResult'; ofType: null; } }; 'poolCreation': { name: 'poolCreation'; type: { kind: 'OBJECT'; name: 'JobResult'; ofType: null; } }; }; };
    'UpdateSignerInput': { kind: 'INPUT_OBJECT'; name: 'UpdateSignerInput'; isOneOf: false; inputFields: [{ name: 'publicKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateSignerNetworkInput': { kind: 'INPUT_OBJECT'; name: 'UpdateSignerNetworkInput'; isOneOf: false; inputFields: [{ name: 'active'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; }; defaultValue: null }, { name: 'permission'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}