name: Lint & Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/workflows/actions/install
          
      - name: Format
        run: bun run format:all

      - name: Lint
        run: bun run lint:all
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/workflows/actions/install

      - name: Build Everything
        run: bun run build
